var url = "https://script.google.com/macros/s/AKfycbxqzL2thgllk8HyFIC9nJdlpO76MnSKzUAhRTOe8DDziJu3rGI/exec";

var alias;
var testData = {
    "action": "create",
    "alias": "Player",
    "weapon": "BRATON",
    "stats1": "Reload Speed",
    "value1": 66.3,
    "stats2": "Damage vs. Grineer",
    "value2": 58.1,
    "stats3": "Critical Damage",
    "value3": 131.9,
    "disposition": "Flight Speed",
    "valueDisposition": -105.1
};

var weapons = ["ACRID",
    "AFURIS",
    "AKBOLTO",
    "AKBRONCO",
    "AKJAGARA",
    "AKLATO",
    "AKLEX",
    "AKSOMATI",
    "AKSTILETTO",
    "AKMAGNUS",
    "AKVASTO",
    "AKZANI",
    "AMPREX",
    "ANGSTRUM",
    "ARTAX",
    "ATOMOS",
    "ATTICA",
    "AZIMA",
    "BALLISTICA",
    "BOAR",
    "BOLTO",
    "BOLTOR",
    "BRAKK",
    "BRATON",
    "BRONCO",
    "BURST LASER",
    "BURSTON",
    "BUZLOK",
    "CASTANAS",
    "CERNOS",
    "CESTRA",
    "CONVECTRIX",
    "DAIKYU",
    "DERA",
    "DESPAIR",
    "DETH MACHINE RIFLE",
    "DETRON",
    "DRAKGOON",
    "DREAD",
    "DUAL CESTRA",
    "DUAL TOXOCYST",
    "EMBOLIST",
    "EUPHONA PRIME",
    "FERROX",
    "FLUX RIFLE",
    "FURIS",
    "GAMMACOR",
    "GLAXION",
    "GORGON",
    "GRAKATA",
    "GRINLOK",
    "HARPAK",
    "HEK",
    "HEMA",
    "HIKOU",
    "HIND",
    "IGNIS",
    "JAVLOK",
    "KARAK",
    "KOHM",
    "KOHMAK",
    "KRAKEN",
    "KULSTAR",
    "KUNAI",
    "LANKA",
    "LASER RIFLE",
    "LATO",
    "LATRON",
    "LEX",
    "MAGNUS",
    "MARELOK",
    "MITTER",
    "MUTALIST CERNOS",
    "MUTALIST QUANTA",
    "NUKOR",
    "OGRIS",
    "OPTICOR",
    "PANTHERA",
    "PARACYST",
    "PARIS",
    "PENTA",
    "PHAGE",
    "POX",
    "PYRANA",
    "QUANTA",
    "RUBICO",
    "SEER",
    "SICARUS",
    "SIMULOR",
    "SNIPETRON",
    "SOBEK",
    "SOMA",
    "SONICOR",
    "SPIRA",
    "STATICOR",
    "STINGER",
    "STRADAVAR",
    "STRUN",
    "STUG",
    "SUPRA",
    "SWEEPER",
    "SYBARIS",
    "SYNAPSE",
    "TALONS",
    "TETRA",
    "TIBERON",
    "TIGRIS",
    "TONKOR",
    "TORID",
    "TWIN GRAKATAS",
    "TWIN GREMLINS",
    "TWIN KOHMAK",
    "TWIN ROGGA",
    "TWIN VIPERS",
    "TYSIS",
    "VASTO",
    "VECTIS",
    "VIPER",
    "VULKAR",
    "VULKLOK",
    "ZARR",
    "ZHUGE"
];

var stats = [
    "なし",
    "基礎ダメージ",
    "マルチショット",
    "クリティカル確率",
    "クリティカルダメージ",
    "冷気ダメージ",
    "毒ダメージ",
    "電気ダメージ",
    "火炎ダメージ",
    "切断ダメージ",
    "貫通ダメージ",
    "衝撃ダメージ",
    "発射速度（ボウは x2）",
    "リロード速度",
    "弾速",
    "弾薬所持数",
    "マガジンサイズ",
    "貫通距離",
    "対コーパスダメージ",
    "対感染体ダメージ",
    "対グリニアダメージ",
    "状態異常確率",
    "状態異常の持続時間",
    "リコイル",
    "ズーム"
];

var statsSub = {
    "弾薬所持数": "Ammo Maximum",
    "対コーパスダメージ": "Damage vs. Corpus",
    "対感染体ダメージ": "Damage vs. Infested",
    "対グリニアダメージ": "Damage vs. Grineer",
    "冷気ダメージ": "Cold Damage",
    "クリティカル確率": "Critical Chance",
    "クリティカルダメージ": "Critical Damage",
    "基礎ダメージ": "Base Damage",
    "電気ダメージ": "Electric Damage",
    "火炎ダメージ": "Fire Damage",
    "発射速度（ボウは x2）": "Fire Rate",
    "弾速": "Flight Speed",
    "衝撃ダメージ": "Impact Damage",
    "マガジンサイズ": "Magazine Capacity",
    "マルチショット": "Multishot",
    "毒ダメージ": "Poison Damage",
    "貫通距離": "Punch Through",
    "貫通ダメージ": "Puncture Damage",
    "リロード速度": "Reload Speed",
    "切断ダメージ": "Slash Damage",
    "状態異常確率": "Status Chance",
    "状態異常の持続時間": "Status Duration",
    "リコイル": "Recoil",
    "ズーム": "Zoom"
};
